//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : dz3
//  @ File Name : File.cpp
//  @ Date : 9/14/2014
//  @ Author : 
//
//


#include "../Header Files/File.h"
#include "../Header Files/FilesystemVisitor.h"

File::File(string name):content(0), FilesystemObject(name) { }

File::File(string name, byte *fContent):content(fContent), FilesystemObject(name) { }

void File::accept(FilesystemVisitor *v)
{

}

void File::putContent(byte *fContent) //throws WriteFailedException
{
	content = fContent;
}

byte* File::getContent() //throws ReadFailedException
{
	return content;
}

